SET NAMES UTF8;
DROP DATABASE IF EXISTS detection;
CREATE DATABASE detection CHARSET=UTF8;
USE detection;
CREATE TABLE Lp(
    id INT PRIMARY KEY AUTO_INCREMENT,
    Lp FLOAT(3),
    time BIGINT
);
CREATE TABLE Lum(
    id INT PRIMARY KEY AUTO_INCREMENT,
    lum FLOAT(3),
    time BIGINT
)
