SET NAMES UTF8;
DROP DATABASE IF EXISTS detect;
CREATE DATABASE detect CHARSET=UTF8;
USE detect;
CREATE TABLE detect(
    id INT PRIMARY KEY AUTO_INCREMENT,
    lum FLOAT(8),
    Lp FLOAT(8),
    time BIGINT
);